/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FixeddepositsRouteImport } from './routes/fixeddeposits'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as TransfersVerifyRouteImport } from './routes/transfers.verify'
import { Route as TransfersTransferlimitRouteImport } from './routes/transfers.transferlimit'
import { Route as TransfersManagebeneficiariesRouteImport } from './routes/transfers.managebeneficiaries'
import { Route as PaymentsCategoryRouteImport } from './routes/payments.$category'
import { Route as CardsBlockCardRouteImport } from './routes/cards.block-card'
import { Route as ApiSmsRouteImport } from './routes/api/sms'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FixeddepositsRoute = FixeddepositsRouteImport.update({
  id: '/fixeddeposits',
  path: '/fixeddeposits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransfersRoute,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaymentsRoute,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRoute,
} as any)
const TransfersVerifyRoute = TransfersVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => TransfersRoute,
} as any)
const TransfersTransferlimitRoute = TransfersTransferlimitRouteImport.update({
  id: '/transferlimit',
  path: '/transferlimit',
  getParentRoute: () => TransfersRoute,
} as any)
const TransfersManagebeneficiariesRoute =
  TransfersManagebeneficiariesRouteImport.update({
    id: '/managebeneficiaries',
    path: '/managebeneficiaries',
    getParentRoute: () => TransfersRoute,
  } as any)
const PaymentsCategoryRoute = PaymentsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PaymentsRoute,
} as any)
const CardsBlockCardRoute = CardsBlockCardRouteImport.update({
  id: '/block-card',
  path: '/block-card',
  getParentRoute: () => CardsRoute,
} as any)
const ApiSmsRoute = ApiSmsRouteImport.update({
  id: '/api/sms',
  path: '/api/sms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/cards': typeof CardsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fixeddeposits': typeof FixeddepositsRoute
  '/help': typeof HelpRoute
  '/loans': typeof LoansRoute
  '/offers': typeof OffersRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/cards/block-card': typeof CardsBlockCardRoute
  '/payments/$category': typeof PaymentsCategoryRoute
  '/transfers/managebeneficiaries': typeof TransfersManagebeneficiariesRoute
  '/transfers/transferlimit': typeof TransfersTransferlimitRoute
  '/transfers/verify': typeof TransfersVerifyRoute
  '/cards/': typeof CardsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/dashboard': typeof DashboardRoute
  '/fixeddeposits': typeof FixeddepositsRoute
  '/help': typeof HelpRoute
  '/loans': typeof LoansRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/sms': typeof ApiSmsRoute
  '/cards/block-card': typeof CardsBlockCardRoute
  '/payments/$category': typeof PaymentsCategoryRoute
  '/transfers/managebeneficiaries': typeof TransfersManagebeneficiariesRoute
  '/transfers/transferlimit': typeof TransfersTransferlimitRoute
  '/transfers/verify': typeof TransfersVerifyRoute
  '/cards': typeof CardsIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/transfers': typeof TransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/cards': typeof CardsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fixeddeposits': typeof FixeddepositsRoute
  '/help': typeof HelpRoute
  '/loans': typeof LoansRoute
  '/offers': typeof OffersRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/cards/block-card': typeof CardsBlockCardRoute
  '/payments/$category': typeof PaymentsCategoryRoute
  '/transfers/managebeneficiaries': typeof TransfersManagebeneficiariesRoute
  '/transfers/transferlimit': typeof TransfersTransferlimitRoute
  '/transfers/verify': typeof TransfersVerifyRoute
  '/cards/': typeof CardsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/cards'
    | '/dashboard'
    | '/fixeddeposits'
    | '/help'
    | '/loans'
    | '/offers'
    | '/payments'
    | '/profile'
    | '/signup'
    | '/transactions'
    | '/transfers'
    | '/api/sms'
    | '/cards/block-card'
    | '/payments/$category'
    | '/transfers/managebeneficiaries'
    | '/transfers/transferlimit'
    | '/transfers/verify'
    | '/cards/'
    | '/payments/'
    | '/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/fixeddeposits'
    | '/help'
    | '/loans'
    | '/offers'
    | '/profile'
    | '/signup'
    | '/transactions'
    | '/api/sms'
    | '/cards/block-card'
    | '/payments/$category'
    | '/transfers/managebeneficiaries'
    | '/transfers/transferlimit'
    | '/transfers/verify'
    | '/cards'
    | '/payments'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/cards'
    | '/dashboard'
    | '/fixeddeposits'
    | '/help'
    | '/loans'
    | '/offers'
    | '/payments'
    | '/profile'
    | '/signup'
    | '/transactions'
    | '/transfers'
    | '/api/sms'
    | '/cards/block-card'
    | '/payments/$category'
    | '/transfers/managebeneficiaries'
    | '/transfers/transferlimit'
    | '/transfers/verify'
    | '/cards/'
    | '/payments/'
    | '/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  CardsRoute: typeof CardsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FixeddepositsRoute: typeof FixeddepositsRoute
  HelpRoute: typeof HelpRoute
  LoansRoute: typeof LoansRoute
  OffersRoute: typeof OffersRoute
  PaymentsRoute: typeof PaymentsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TransactionsRoute: typeof TransactionsRoute
  TransfersRoute: typeof TransfersRouteWithChildren
  ApiSmsRoute: typeof ApiSmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixeddeposits': {
      id: '/fixeddeposits'
      path: '/fixeddeposits'
      fullPath: '/fixeddeposits'
      preLoaderRoute: typeof FixeddepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/payments/': {
      id: '/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRoute
    }
    '/transfers/verify': {
      id: '/transfers/verify'
      path: '/verify'
      fullPath: '/transfers/verify'
      preLoaderRoute: typeof TransfersVerifyRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/transfers/transferlimit': {
      id: '/transfers/transferlimit'
      path: '/transferlimit'
      fullPath: '/transfers/transferlimit'
      preLoaderRoute: typeof TransfersTransferlimitRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/transfers/managebeneficiaries': {
      id: '/transfers/managebeneficiaries'
      path: '/managebeneficiaries'
      fullPath: '/transfers/managebeneficiaries'
      preLoaderRoute: typeof TransfersManagebeneficiariesRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/payments/$category': {
      id: '/payments/$category'
      path: '/$category'
      fullPath: '/payments/$category'
      preLoaderRoute: typeof PaymentsCategoryRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/cards/block-card': {
      id: '/cards/block-card'
      path: '/block-card'
      fullPath: '/cards/block-card'
      preLoaderRoute: typeof CardsBlockCardRouteImport
      parentRoute: typeof CardsRoute
    }
    '/api/sms': {
      id: '/api/sms'
      path: '/api/sms'
      fullPath: '/api/sms'
      preLoaderRoute: typeof ApiSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CardsRouteChildren {
  CardsBlockCardRoute: typeof CardsBlockCardRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsBlockCardRoute: CardsBlockCardRoute,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface PaymentsRouteChildren {
  PaymentsCategoryRoute: typeof PaymentsCategoryRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsCategoryRoute: PaymentsCategoryRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

interface TransfersRouteChildren {
  TransfersManagebeneficiariesRoute: typeof TransfersManagebeneficiariesRoute
  TransfersTransferlimitRoute: typeof TransfersTransferlimitRoute
  TransfersVerifyRoute: typeof TransfersVerifyRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
}

const TransfersRouteChildren: TransfersRouteChildren = {
  TransfersManagebeneficiariesRoute: TransfersManagebeneficiariesRoute,
  TransfersTransferlimitRoute: TransfersTransferlimitRoute,
  TransfersVerifyRoute: TransfersVerifyRoute,
  TransfersIndexRoute: TransfersIndexRoute,
}

const TransfersRouteWithChildren = TransfersRoute._addFileChildren(
  TransfersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CardsRoute: CardsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FixeddepositsRoute: FixeddepositsRoute,
  HelpRoute: HelpRoute,
  LoansRoute: LoansRoute,
  OffersRoute: OffersRoute,
  PaymentsRoute: PaymentsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TransactionsRoute: TransactionsRoute,
  TransfersRoute: TransfersRouteWithChildren,
  ApiSmsRoute: ApiSmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
